{
 "title": "Commit Collective",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Commits",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('hour', stamp) as \"time\"\n  ,count(1)\nFROM git_metrics\nwhere $__timeFilter(stamp)\nGroup by date_trunc('hour', stamp)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Files Changed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('hour', stamp) as \"time\"\n  ,sum(files_changed)\nFROM git_metrics\nwhere $__timeFilter(stamp)\nGroup by date_trunc('hour', stamp)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Languages",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "  SELECT\n    UNNEST(extensions) as Extention, count(1) commits\n  FROM git_metrics\n  WHERE\n    $__timeFilter(stamp)\n    and extensions <> '{}'\n  group by UNNEST(extensions)"
    }
   ]
  },
  {
   "title": "Insertions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('hour', stamp) as \"time\"\n  ,sum(insertions)\nFROM git_metrics\nwhere $__timeFilter(stamp)\nGroup by date_trunc('hour', stamp)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Deletions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('hour', stamp) as \"time\"\n  ,sum(deletions)\nFROM git_metrics\nwhere $__timeFilter(stamp)\nGroup by date_trunc('hour', stamp)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Changes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  stamp as time,\n  1 as commits,\n  files_changed,\n  insertions,\n  deletions\nFROM\n  git_metrics\nWHERE\n  $__timeFilter(stamp)\nORDER BY stamp"
    }
   ]
  },
  {
   "title": "Team leaderboard last week",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  team_name AS \"Team\",\n  sum(files_changed) AS \"Files\",\n  sum(insertions) AS \"Insertions\",\n  sum(deletions) AS \"Deletions\"\nFROM git_metrics\nwhere team_name <> 'UNKNOWN'\nand $__timeFilter(stamp)\nGROUP BY team_name\nORDER BY (sum(insertions) + sum(deletions)) desc"
    }
   ]
  },
  {
   "title": "Commits Leaderboard",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  username AS \"User\",\n  count(1) AS \"Commits\"\nFROM git_metrics\nWHERE username <> 'UNKNOWN'\nand $__timeFilter(stamp)\nGROUP BY username\nORDER BY count(1) desc"
    }
   ]
  },
  {
   "title": "Files Changed Leaderboard",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  username AS \"User\",\n  sum(files_changed) AS \"Files\"\nFROM git_metrics\nWHERE\n  username != 'UNKNOWN'\nand $__timeFilter(stamp)\nGROUP BY username\nORDER BY sum(files_changed) desc"
    }
   ]
  },
  {
   "title": "Insertions Leaderboard",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  username AS \"User\",\n  sum(insertions) AS \"Insertions\"\nFROM git_metrics\nWHERE username <> 'UNKNOWN'\nand $__timeFilter(stamp)\nGROUP BY username\nORDER BY sum(insertions) desc"
    }
   ]
  },
  {
   "title": "Deletions Leaderboard",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  username AS \"User\",\n  sum(deletions) AS \"Deletions\"\nFROM git_metrics\nwhere username <> 'UNKNOWN'\nand $__timeFilter(stamp)\nGROUP BY username\nORDER BY sum(deletions) desc"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 18 },
   "options": {
    "content": "<br/><br/><br/>\r\n<img src=\"https://www.sourceallies.com/img/logo/source-allies-logo-final.png\"/>"
   },
   "targets": [
    { "region": "default", "statistics": [ "Average" ] }
   ]
  }
 ]
}