name: Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release version"
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Create Release ${{ github.event.inputs.release_version }} On ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./Hookstaller/
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            name: Ubuntu
          - os: windows-latest
            name: Windows
          - os: macOS-latest
            name: MacOS
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose --release
      - uses: papeloto/action-zip@v1
        with:
          files: |
            Hookstaller/target/release/installer
            Hookstaller/target/release/installer.exe
            Hookstaller/target/release/post-commit
            Hookstaller/target/release/post-commit.exe
          recursive: false
          dest: Artifact.zip
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.name }} Release ${{ github.event.inputs.release_version }}
          if-no-files-found: error
          path: ${{ github.workspace }}/Artifact.zip
        
